name: wildfire-lake-productivity
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  
  # Data management
  - requests
  - pyarrow
  - feather-format
  
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver
  - scikit-learn
  - pydot
  - python-graphviz

  # Spatial packages
  - rasterio  
  - pyproj
  - rasterstats
  - geopy
  - geopandas
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - geocoder
  - shapely
  - basemap
  - elevation
  
  # GEE packages
  - google-colab
  - earthengine-api
  - geemap
  - hydrofunctions
  - altair

  # Natural language processing
  - nltk 
  - textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse