name: wildfire-lake-productivity
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  
  # Data management
  - requests
  - pyarrow
  - feather-format
  
  # Core scientific python
  - numpy
  - matplotlib
  - seaborn

  # Spatial packages
  - rasterio  
  - pyproj
  - rasterstats
  - geopy
  - geopandas
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - shapely
  - earthengine-api
  - geemap
  - basemap

  # Natural language processing
  - nltk 
  - textblob

  # Jupyter Environment
  - autopep8
  - jupyterlab
  - notebook
  - jupyter_contrib_nbextensions
